### ISSUE TITLE
Botão para cadastrar job

### ISSUE THREAD

**Issue by germanotm** [cfaz-net/cfaz-site#2]
O Alexandre sentiu falta do botão de criar  usuário job. Quando fomo procurar vimos que realmente não tem mais esse botão.

Adicionar o botão de Cadastrar par job parecido com o que tinha no site antigo.

Site antigo:
https://max.cfaz.net/site/cfazjob

No novo site tem que entrar na página de telerradiologia. O gustavo sugeriu colocar depois dos blocos brancos, antes do laranja.
https://cfaz.net/teleradiology.html

**Comment by scheillaartifon** [comment]
Implementado sessão de cadastro no CfazJob na tela de telerradiologia do site.
