### ISSUE TITLE
Separar Usuário de Visitante no Google Analytics

### ISSUE THREAD

**Issue by gcgustavo** [cfaz-net/cfaz-site#3]
**Cronograma**
Dada inicio: 
Previsão termino: 
Data fim:

**Stakehoders**
"Número de visitantes no site" é uma métrica necessária para a Equipe de Marketing da Cfaz.net

**Objetivo do usuário**
Separar Usuários de Visitantes no Google Analytics

**Descrição do problema**
Hoje, ao acessar os relatório do google analytics, estamos vendo os números de todas as pessoas que acessaram nosso site. A grande maioria delas já é nosso cliente.

Precisamos criar uma maneira para separar usuários (pessoas que entraram no site e depois clicaram direto no link do max ou do manager) dos visitantes, aquelas pessoas que entraram no site apenas para conhecer .

Shirley e Thales do nosso Marketing também podem ajudar com o Google Analytics!

**Comment by WillianVarela** [comment]
Conversado com o Gustavo, o mesmo relatou que a alteração cumpriu os requisitos.
