### ISSUE TITLE
Formulário de Solicitação de Contato não funciona

### ISSUE THREAD

**Issue by gcgustavo** [cfaz-net/cfaz-site#4]
Só o formulário que está num modal está funcionando - quando clicamos nos botões "Quero falar com um Consultor".

O formulário que está fixo na página, logo abaixo de depoimentos de clientes, não está funcionando: o contato não é criado no Hubspot.

Para testar se o formulário está funcionando, é só conferir se o contato foi criado no Hubspot. Aqui a listagem dos contatos, ordenados pelo mais recente primeiro: https://app.hubspot.com/contacts/6654092/objects/0-1/views/all/list

**Comment by scheillaartifon** [comment]
Está enviando todos os formulários. O que acontece é que quando o usuário já tem um lead cadastrado no hubspot e o mesmo tenta fazer um novo envio das informações utilizando o mesmo e-mail, o hubspot atualiza as informações do usuário e mantem o lead que já existia na base, sem criar vários formuláirios com o mesmo e-mail.
