### ISSUE TITLE
Adicionar video institucional em português e atualizar equipe

### ISSUE THREAD

**Issue by scheillaartifon** [cfaz-net/cfaz-site#5]
Atualizar os dados abaixo:

- [x] Adicionar o video institucional em português e manter a imagem da Cfaz se o usuário estiver vendo o site em Inglês ou Espanhol
- [x] Atualizar os membros da equipe segundo o card https://trello.com/c/hF2tBDyW/1012-fotos-site
- [x] Arrumar layout do site no celular depois que colocou o video.

**Comment by germanotm** [comment]
O video quebrou o layout do site no celular. O tamanho não ajustou para o tamanho da tela:


![Captura de tela de 2021-08-19 10-02-14](https://user-images.githubusercontent.com/169503/130073181-f6771c84-06c8-438c-97e9-3d2b14245879.png)

**Comment by germanotm** [comment]
Verifiquei no meu celular, o layout ficou correto.
